language: python
python:
  - 3.6
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_223a70cebde4_key -iv $encrypted_223a70cebde4_iv -in publish-key.enc -out publish-key -d
  - chmod u=rw,og= ~/.ssh/publish-key
  - git remote set-url origin git@github.com:pythonbrasil/pythonbrasilblog.git
install:
  - pip install pelican
  - pip install ghp-import
script: make github
